### ISSUE TITLE
Process exited when use plugin "Custom VSCode UI CSS".

### ISSUE THREAD

**Issue by MuShann** [Enter-tainer/typst-preview#110] opened 2023-09-04 11:52 UTC
**Describe the bug**
Typst-preview process exited with code 101 after using plugin "Custom VSCode UI CSS" change ```#imageContainer > svg``` css.

Custom VSCode UI CSS: https://marketplace.visualstudio.com/items?itemName=kencocaceo.customvscodeuicss

**Comment by MuShann** [comment] 2023-09-04 12:26
Sorry, this seems to be a problem with Custom VSCode UI CSS. I missed the VSCode error message.

**Comment by Enter-tainer** [comment] 2023-09-04 12:59
Cannot reproduce. Is this really related to "Custom VSCode UI CSS"? Also I remember there is a long issue template. If you can fill that perhaps we can better fix that issue.

**Comment by MuShann** [comment] 2023-09-05 04:19
Sorry I lost the log files because in the process of trying to fix I reinstalled vscode and cleared the cache. It seems that the wrong font path caused typst-preview to report an error after the plug-in "Custom VSCode UI CSS" restarted vscode. Now I can use it normally, thanks for your reply.

**Comment by Enter-tainer** [comment] 2023-09-05 04:53
Glad to hear it works now. I will close this issue.

**Closed by Enter-tainer** 2023-09-05 04:53 UTC
