### ISSUE TITLE
mangled output (possibly incremental compiling issue)

### ISSUE THREAD

**Issue by Enter-tainer** [Enter-tainer/typst-preview#141] opened 2023-10-20 01:41 UTC
None of it is reliable though, it's just like it'll sometimes render some text wrong and the moment I reload the preview it fixes it
```
#let should_indent = state("should_indent", false)
#show par: it => should_indent.display(s => if s {
    pad(left: 1cm, it)
} else {
    it
})
#show heading.where(level: 1): it => [
    #should_indent.update(false)
    #it
]
#show heading.where(level: 2): it => [
    #it
    #should_indent  //.update(true)
]

= Section

== Level 2
Text in here!
=== Level 3
And also here
== Level 2 again
And even here!

= Level 1 again
Here too
```

reported by yasha on discord
![image-4.png](https://github.com/Enter-tainer/typst-preview/assets/25521218/6a4ebf39-6857-4c46-9d8f-0a685c0ee38f)

**Comment by yaksher** [comment] 2023-10-20 01:51
I’ve had this issue semi-regularly and reloading always fixes it (I’m Yasha on discord)

**Comment by Enter-tainer** [comment] 2023-10-20 01:54
hi @yaksher do you have an edit sequence can reliably reproduce it? this can greatly help us debugging!

the colored text looks like some highlighted code. but currently the code doesnt contain any text. i guess it comes from previous editing?

**Comment by yaksher** [comment] 2023-10-20 01:59
The colored text is from how state renders when it renders correctly. No reliable edit sequences but if I encounter one I can try to add it here. The reason I’ve not bothered to report it myself is the lack of reproducibility lol. “Sometimes it gets mangled lol” is not a very useful bug report

**Comment by Enter-tainer** [comment] 2023-10-20 05:50
ground truth: 
<img width="389" alt="image" src="https://github.com/Enter-tainer/typst-preview/assets/25521218/977457f3-67ae-4a62-a46c-b4d08a655e7f">

looks like the color is okay but glyphs are mapped to wrong ones. comparing the 2 image we can see that `t` maps to `3` and many other similar mappings.

**Comment by Enter-tainer** [comment] 2023-10-20 05:52
What is strange it the monospaced `ls` in your image. monospaced font doesn't present in this doc. And it shouldn't appear. Is this code piece comes from a larger document? Or this comes from your previous editing?

**Comment by yaksher** [comment] 2023-10-20 06:12
The code provided is the entire file. I don't think it comes from previous editing, but I guess it could. There wasn't much of it.

**Comment by Enter-tainer** [comment] 2023-10-20 06:14
okay the ls may comes from `false`, which is monospace

**Comment by yaksher** [comment] 2023-10-23 08:06
```
Consider two arbitrary values $i, j in {0, dots, p - 1}$ with $i neq j$. Then $
            PP{h_(a b)(i) = h_(a b)(j)} &= PP{a + i b equiv_n a + j b}\
            &= PP{i b equiv_n j b} \
        $
```

<img width="447" alt="image" src="https://github.com/Enter-tainer/typst-preview/assets/5308181/cf139856-8995-40ae-ba56-b18e79ce82d6">

I don't know how to reproduce necessarily, but here's another example. If you reply to this quickly enough with requests for specific things I might try, I'm happy to. Both mangled spots respond the same way to changes:

- Removing the closing brace deletes the Y at the end and makes the bold 3 into an opening brace
- Removing the opening brace deletes the 3 at the beginning and makes the Y into a closing brace
- Removing the equiv sign makes that line render correctly
- Replacing the equiv sign with an equal sign has the equal render correctly, but the opening brace becomes a `v` and the closing brace disappears entirely
- If I paste the entire math equation anywhere in the document, it renders the same broken way

**Comment by Enter-tainer** [comment] 2023-10-23 08:10
Thanks for this detailed reproduction guide! I will try this when I leave work. BTW, can you provide more info about your system? You may get them from `About` in VSCode. like this:

```
version: 1.83.1 (Universal)
commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
data: 2023-10-10T23:46:55.789Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0
```
And also, the extension version, and whether you are using on a remote machine.

**Comment by yaksher** [comment] 2023-10-23 08:15
It's not much of a reproduction guide, since I suspect that this will all disappear the moment I reload the preview.
```
Version: 1.83.1 (Universal)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:46:55.789Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 22.6.0
```
I believe I'm on v0.8.1 of Typst preview—specifically, my VS Code has installed version v0.8.2 but I haven't reloaded VS Code, so it should still be using v0.8.1.

This is not a remote machine.

**Comment by Enter-tainer** [comment] 2023-10-23 08:19
> I believe I'm on v0.8.1 of Typst preview—specifically, my VS Code has installed version v0.8.2 but I haven't reloaded VS Code, so it should still be using v0.8.1.

BTW, You may reload it and see if bug still happens. v0.8.2 fix some race condition in incremental rendering.

**Comment by yaksher** [comment] 2023-10-23 08:21
I switched off the tab and back, which fixed it for now, but I'll update my version of Typst preview and let you know if the issue reoccurs (eventually) or seems to be gone; it does fit a race condition since it happens in very inconsistent and strange ways.

**Comment by Myriad-Dreamin** [comment] 2024-01-03 14:19
There is a newly found bug in incremental font transfer (hasn't been fixed). I expect it is related to this issue. later fix would close this issue.

**Comment by yaksher** [comment] 2024-01-03 17:33
I think I did encounter it once or twice in Typst Preview 0.8.2 but the frequency dropped radically from 0.8.1.

**Closed** 2024-01-13 15:57 UTC
Labels: bug
