### ISSUE TITLE
[FR] Show page breaks

### ISSUE THREAD

**Issue by KronosTheLate** [Enter-tainer/typst-preview#122] opened 2023-09-20 11:55 UTC
In the current previewer, page breaks are not shown:
![image](https://github.com/Enter-tainer/typst-preview/assets/61620837/1fe9529a-3cf0-46b6-bb19-ac75049e5943)

This makes it hard to understand why the spacing is as it is sometimes, which blurs the lines between spacing that needs fixing and spacing that looks the best given the pagebreaks. Could at least an option be added to allow showing a gap between pages?

**Comment by KronosTheLate** [comment] 2023-09-20 13:48
Cool! Is that PR on track to get merged once it is working as intended? If yes, then this issue has no reason to exist.

**Comment by Enter-tainer** [comment] 2023-09-20 14:01
we will close this and #80 when the pr get merged 👍

**Comment by Myriad-Dreamin** [comment] 2023-09-20 15:39
Update: It has been worked as intended! Though we leave customization out of current PR, I believe we have a good default setting:
+ The border width is window-aware.
+ The color page's border (page break) is fixed in `--vscode-editor-background`.
+ The page's background is fixed in `white` color, but you can still override a background at typst side, as the screenshot shown.
  via `set page(fill: rgb("#1a1b26").lighten(10%))`.

![image](https://github.com/Enter-tainer/typst-preview/assets/35292584/7d1adade-454b-4afb-9832-fb29d62d0b81)

**Closed** 2023-09-24 13:35 UTC
