### ISSUE TITLE
Jump to code from subscript content does not work for some subscripts

### ISSUE THREAD

**Issue by ghost** [Enter-tainer/typst-preview#181] opened 2023-11-12 20:42 UTC
**Describe the bug**
When clicking in the preview window the following does not jump to the code (when clicking on the subscript content `2a`):

```typst
#lorem(50)

In the following subscript only the jump to the $X$ works, but not to the subscript content: $X_"2a"$
Other subscripts work: $X_12$

#lorem(50)
```

**Expected behavior**
The jumping behaviour for `$X_"2a"$` should be the same as for `$X_12$` in all parts.

**Package/Software version:**

VSCode version(Help -> About):
```plain
Version: 1.84.2 (user setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
```

**Comment by Myriad-Dreamin** [comment] 2023-11-13 06:13
The span information is provided by typst compiler, and it doesn't provide a such information for raw strings.

We may convert it to a upstream issue when we double confirmed that.

**Comment by gfpj** [comment] 2023-11-13 10:34
Since jumping to the X works, maybe this could be used as target position.

**Comment by Enter-tainer** [comment] 2024-03-21 13:53
This also works in 0.11.0. So I close this

**Closed by Enter-tainer** 2024-03-21 13:53 UTC
